#!/usr/bin/env bash

# TODO: Display weather of IIIT, Lucknow
# For more information see: https://wttr.in/:help
read -p "Enter name of the location: " in
# If user will enter name of the location with spaces we will convert it to required format
# /~Eiffel+tower          # any location (+ for spaces)
old_IFS=IFS;
IFS=' '
read -ra array <<< "$in"
new="~"
for word in "${array[@]}"
do
new="${new}+${word}"
done
echo $(curl wttr.in/${new})
IFS=old_IFS