#!/usr/bin/env bash

# TODO (Run this script as): color magenta && echo hello && color reset

color() {
    echo -ne "\033[$1;$2m"
}

declare -A color_mapping=(
    # TODO: Add more color values
    # Refer bash color codes
    ['reset']='0 00'
    ['black']='0 30'
    ['red']='0 31'
    ['green']='0 32'
    ['yellow']='0 33'
    ['blue']='0 34'
    ['magenta']='0 35'
    ['cyan']='0 36'
    ['white']='0 37'
    ['bold_black']='1 30'
    ['bold_red']='1 31'
    ['bold_green']='1 32'
    ['bold_yellow']='1 33'
    ['bold_blue']='1 34'
    ['bold_magenta']='1 35'
    ['bold_cyan']='1 36'
    ['bold_white']='1 37'
)

color ${color_mapping[$1]}

echo "hello"
