#!/usr/bin/env bash

# grep -E 'Tctl|Tdie|Package id' /sys/class/hwmon/hwmon*/temp*_label | head -n1 | cut -d':' -f1 | sed 's/label/input/' | xargs cat

# Following script outputs current cpu die temperature in milidegree-celcius, convert it to celcius and fahrenheit and display as:
#
# Celcius: 42.0 C
# Fahrenheit: 107.6 F

temp_mk=$(grep -E 'Tctl|Tdie|Package id' /sys/class/hwmon/hwmon*/temp*_label | head -n1 | cut -d':' -f1 | sed 's/label/input/' | xargs cat)

# Convert the temperature to Celsius
temp_c=$(echo "scale=2; $temp_mk / 1000" | bc)

# Convert the temperature to Fahrenheit
temp_f=$(echo "scale=2; $temp_c * 9 / 5 + 32" | bc)

echo "Celsius: $temp_c C"
echo "Fahrenheit: $temp_f F"