#!/usr/bin/env bash

#Extract CPU die temperature in milli-Celsius
temp_milli_celsius=$(grep -E 'Tctl|Tdie|Package id' /sys/class/hwmon/hwmon*/temp*_input | head -n1 | xargs cat)

#milli-Celsius to Celsius
temp_celsius=$(echo "scale=1; $temp_milli_celsius / 1000" | bc)

#Celsius to Fahrenheit
temp_fahrenheit=$(echo "scale=1; $temp_celsius * 9 / 5 + 32" | bc)

# Output the formatted temperature
echo "Celsius: $temp_celsius C"
echo "Fahrenheit: $temp_fahrenheit F"

