#!/usr/bin/env bash

# Arranges the files by grouping them into folder of their extension name
# TODO: Run this script in your downloads folder

require() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed";exit 1; }
}

require fd
require egrep

declare -A special_cases=( 
    ['^.(tar.|tbz)$']='tar'
    ['\.(jpe?g|png|gif|bmp|svg|psd|tiff)$']='images'
    ['\.(mp3|wav|flac|aac|ogg|wma|m4a)$']='audio'
    ['\.xlsx?$']='xls'
    ['\.docx?$']='doc'
    ['\.pptx?$']='ppt'
    ['\.pdf$']='pdf'
    ['\.html?$']='html'
    ['\.css$']='css'
    ['\.js$']='js'
    ['\.cpp$']='cpp'
    ['\.c$']='c'
    ['\.java$']='java'
    ['\.py$']='python'
    ['\.sh$']='sh'
    # TODO: Add your own pattern here for similar file types appropriately
    # Refer https://regex101.com/ & https://github.com/ziishaned/learn-regex/ for explaination and writing patterns
    # These (regex) are same as ones used in sed command
)

fd -tf -d1 \
| while read file; do
    folder="$PWD/${file##*.}"
    for regex in "${!special_cases[@]}"; do
        (echo "$file" | egrep -q "$regex") && {
            folder="$PWD/${special_cases[$regex]}"
            break
        }
    done

    mkdir -p "$folder"
    mv "$file" "$folder"
done

