#!/usr/bin/env bash

# Arranges the files by grouping them into folders of their extension name
# TODO: Run this script in your downloads folder

require() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed";exit 1; }
}

require fd
require grep

declare -A special_cases=(
    ['^*.(tar.*|tbz)$']='tar'
    ['\.rar$']='rar'
    ['\.doc$']='doc'
    ['\.(jpg|jpeg|png|gif|bmp)$']='img'
    ['\.mp3$']='mp3'
    ['\.(mp4|avi|mkv)$']='videos' # Example pattern for grouping video files
    # TODO: Add your own pattern here for similar file types appropriately
    # Refer https://regex101.com/ & https://github.com/ziishaned/learn-regex/ for explanation and writing patterns
    # These (regex) are same as ones used in sed command
)

fd -tf -d1 \
| while read file; do
    folder="$PWD/${file##*.}"
    for regex in "${!special_cases[@]}"; do
        (echo "$file" | grep -E -q "$regex") && {
            folder="$PWD/${special_cases[$regex]}"
            break
        }
    done

    # Check if the directory already exists before creating it
    if [ ! -d "$folder" ]; then
        mkdir -p "$folder"
    fi

    mv "$file" "$folder"
done
