#!/usr/bin/env bash

output_dir="$(pwd)/Music"

fd . -e 'mp4' | while read -r file; do

    filename_no_ext="${file%.*}" # clips/Sequence04
    # echo "$filename_no_ext"
    filename_with_ext="${file}" #clips/Sequence04.mp4
    # echo "$filename_with_ext"

    output_file="${output_dir}/${filename_no_ext}"

    #making corresponding folders here
    dir_name=$(dirname "$filename_with_ext") # clips
    # echo "$dir_name"
    mkdir -p "$output_dir/$dir_name" #makes pwd/music/clips

    input="$(pwd)/$filename_with_ext" # /home/baka/Pictures/clips/Sequence04.mp4
    output="${output_file}.mp3"       # /home/baka/Pictures/Music/clips/Sequence04.mp3

    # echo "$output"

    ffmpeg -i "$input" "$output"

done
