#!/bin/bash
extract_audio() {
    local input_folder="$1"
    local output_folder="$2"

    find "$input_folder" -type f -name "*.mp4" | while IFS= read -r file; do
        filename=$(basename "$file" .mp4)
        mkdir -p "$output_folder/$(dirname "${file#$input_folder}")"
        ffmpeg -i "$file" -vn -acodec libmp3lame -q:a 2 "$output_folder/${filename}.mp3" < /dev/null
    done
}
if [ -z "$1" ]; then
    echo "Usage: $0 <input_folder>"
    exit 1
fi

input_folder="$1"
output_folder="Music"
extract_audio "$input_folder" "$output_folder"