#!/bin/bash

password_randomizer() {
    local length=$1
    local password=$(cat /dev/urandom | tr -dc 'A-Za-z0-9!@#$%^&*()' | fold -w $length | head -n 1)
    echo $password
}


generate_password $1
