#!/usr/bin/env bash

# TODO: Make it print out permissions of the given files in octal format
#
# E.g.:
# $ perms weather ../README.md
# 775 weather
# 664 ../README.md

perms() {
    for file in "$@"; do
        if [ -e "$file" ]; then
            # Get permissions in octal format
            perm_octal=$(stat -c '%a' "$file")
            echo "$perm_octal $file"
        else
            echo "File $file does not exist."
        fi
    done
}