#!/usr/bin/env bash

# TODO: Make it print out permissions of the given files in octal format
#
# E.g.:
# $ perms weather ../README.md
# 775 weather
# 664 ../README.md



for file in "$@";
do
  # Getting octal permissions using stat
  permissions=$(stat -c "%a" "$file")

  # Displaying filename and permissions
  echo "$permissions  $file"
done
