#!/usr/bin/env bash

# Remove all the binary files (usually made after gcc) present inside the current directory
# Refer "man find" for more information, you can also use modern tool like fd instead of find

# Using find command to locate binary files and remove them
find . -type f -executable -exec file {} + | grep -i 'executable' | cut -d: -f1 | xargs rm -f

# Alternatively, you can use fd command if available
# fd -I -t f -x rm -f
