#!/usr/bin/env bash

# Remove all binary files in the current directory
find . -type f -executable -exec file {} \; | grep -i 'executable' | cut -d: -f1 | xargs rm -f
echo "All binary files in the current directory removed successfully"
