#!/usr/bin/env bash



# Iterate through each Git repository found in the current directory
find . -name .git -type d -prune -exec bash -c '
 for repo_dir; do
   cd "$repo_dir/.." || exit

   # get ingnore file pattern 
   ignored_patterns=$(cat .gitignore | grep -v "^#")

   # Remove matching files (excluding .gitignore itself)
   find . -type f ! -name .gitignore -regex "$ignored_patterns" -delete
 done
' \;

