#!/usr/bin/env bash

# TODO: Display weather of IIIT, Lucknow
# For more information see: https://wttr.in/:help



# Taking user input for location
read -p "Enter the location: " location

# Check if location is empty
if [ -z "$location" ]; then
  echo "Error: Please enter a location."
  exit 1
fi

# Display weather information using wttr.in with color option
curl wttr.in/"$location?m"