#!/usr/bin/env bash

# Extract the wifi username (SSID)
# Refer: "iw dev wlan0 link" command output for this

ssid=$(iwconfig wlan0 | awk -F '"' '/ESSID/ {print $2}')

if [ -n "$ssid" ]; then
    echo "WiFi SSID: $ssid"
else
    echo "WiFi SSID not available"
fi
