#!/usr/bin/env bash

# TODO: Make a script to download youtube video from given timeframes
#
# E.g.: youtube-time 2:00 4:00 tutorial.mkv "https://www.youtube.com/watch?v=SPwyp2NG-bE"
# The above command should create a output file which contains the video from 2 min to 4 min.
#
# Refer: youtube-dl and ffmpeg commands for this

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 start_time end_time output_file video_url"
    exit 1
fi

start_time=$1
end_time=$2
output_file=$3
video_url=$4

youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' -o "video.mp4" "$video_url"

ffmpeg -i "video.mp4" -ss "$start_time" -to "$end_time" -c:v copy -c:a copy "$output_file"

rm "video.mp4"
